name: Docker
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Image
        run: |
          docker login --username pavelbesedinsky --password ${{ secrets.GH_DOCKER_PAT }} ghcr.io
          docker build . --tag ghcr.io/pavelbesedinsky/auth.pilotiv:latest
          docker push ghcr.io/pavelbesedinsky/auth.pilotiv:latest